import { defineConfig } from "orval";

const apiBaseUrl = process.env.VITE_API_BASE_URL ?? "http://localhost:8081";

export default defineConfig({
  mira: {
    input: {
      target: "./mira-api.yaml",
    },
    output: {
      target: "./src/api/mira.ts",
      schemas: "./src/api/model",
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      baseUrl: apiBaseUrl,
      override: {
        header: () =>
          "/* eslint-disable */\n// @ts-nocheck\n/**\n * Generated by orval. Do not edit manually.\n */",
        mutator: {
          path: "./src/lib/authFetch.ts",
          name: "authFetch",
        },
      },
    },
  },
});
