/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateListingRouteImport } from './routes/create-listing'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as RegisterRouteRouteImport } from './routes/register/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterRoleRouteImport } from './routes/register/role'
import { Route as RegisterPhotoRouteImport } from './routes/register/photo'
import { Route as RegisterNameRouteImport } from './routes/register/name'
import { Route as RegisterDoneRouteImport } from './routes/register/done'
import { Route as RegisterAddressRouteImport } from './routes/register/address'
import { Route as RegisterAboutRouteImport } from './routes/register/about'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateListingRoute = CreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRouteRoute = RegisterRouteRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterRoleRoute = RegisterRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterPhotoRoute = RegisterPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterNameRoute = RegisterNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterDoneRoute = RegisterDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterAddressRoute = RegisterAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const RegisterAboutRoute = RegisterAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RegisterRouteRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/styleguide': typeof StyleguideRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/register/about': typeof RegisterAboutRoute
  '/register/address': typeof RegisterAddressRoute
  '/register/done': typeof RegisterDoneRoute
  '/register/name': typeof RegisterNameRoute
  '/register/photo': typeof RegisterPhotoRoute
  '/register/role': typeof RegisterRoleRoute
  '/register/': typeof RegisterIndexRoute
  '/listings/$listingId/book': typeof ListingsListingIdBookRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/styleguide': typeof StyleguideRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/register/about': typeof RegisterAboutRoute
  '/register/address': typeof RegisterAddressRoute
  '/register/done': typeof RegisterDoneRoute
  '/register/name': typeof RegisterNameRoute
  '/register/photo': typeof RegisterPhotoRoute
  '/register/role': typeof RegisterRoleRoute
  '/register': typeof RegisterIndexRoute
  '/listings/$listingId/book': typeof ListingsListingIdBookRoute
  '/listings/$listingId': typeof ListingsListingIdIndexRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/create-listing': typeof CreateListingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/styleguide': typeof StyleguideRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/register/about': typeof RegisterAboutRoute
  '/register/address': typeof RegisterAddressRoute
  '/register/done': typeof RegisterDoneRoute
  '/register/name': typeof RegisterNameRoute
  '/register/photo': typeof RegisterPhotoRoute
  '/register/role': typeof RegisterRoleRoute
  '/register/': typeof RegisterIndexRoute
  '/listings/$listingId_/book': typeof ListingsListingIdBookRoute
  '/listings/$listingId/': typeof ListingsListingIdIndexRoute
  '/profile/$userId/edit': typeof ProfileUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/calendar'
    | '/create-listing'
    | '/login'
    | '/profile'
    | '/styleguide'
    | '/profile/$userId'
    | '/register/about'
    | '/register/address'
    | '/register/done'
    | '/register/name'
    | '/register/photo'
    | '/register/role'
    | '/register/'
    | '/listings/$listingId/book'
    | '/listings/$listingId/'
    | '/profile/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/create-listing'
    | '/login'
    | '/profile'
    | '/styleguide'
    | '/profile/$userId'
    | '/register/about'
    | '/register/address'
    | '/register/done'
    | '/register/name'
    | '/register/photo'
    | '/register/role'
    | '/register'
    | '/listings/$listingId/book'
    | '/listings/$listingId'
    | '/profile/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/calendar'
    | '/create-listing'
    | '/login'
    | '/profile'
    | '/styleguide'
    | '/profile/$userId'
    | '/register/about'
    | '/register/address'
    | '/register/done'
    | '/register/name'
    | '/register/photo'
    | '/register/role'
    | '/register/'
    | '/listings/$listingId_/book'
    | '/listings/$listingId/'
    | '/profile/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRouteRoute: typeof RegisterRouteRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CreateListingRoute: typeof CreateListingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StyleguideRoute: typeof StyleguideRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-listing': {
      id: '/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof CreateListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/role': {
      id: '/register/role'
      path: '/role'
      fullPath: '/register/role'
      preLoaderRoute: typeof RegisterRoleRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/photo': {
      id: '/register/photo'
      path: '/photo'
      fullPath: '/register/photo'
      preLoaderRoute: typeof RegisterPhotoRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/name': {
      id: '/register/name'
      path: '/name'
      fullPath: '/register/name'
      preLoaderRoute: typeof RegisterNameRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/done': {
      id: '/register/done'
      path: '/done'
      fullPath: '/register/done'
      preLoaderRoute: typeof RegisterDoneRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/address': {
      id: '/register/address'
      path: '/address'
      fullPath: '/register/address'
      preLoaderRoute: typeof RegisterAddressRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/register/about': {
      id: '/register/about'
      path: '/about'
      fullPath: '/register/about'
      preLoaderRoute: typeof RegisterAboutRouteImport
      parentRoute: typeof RegisterRouteRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegisterRouteRouteChildren {
  RegisterAboutRoute: typeof RegisterAboutRoute
  RegisterAddressRoute: typeof RegisterAddressRoute
  RegisterDoneRoute: typeof RegisterDoneRoute
  RegisterNameRoute: typeof RegisterNameRoute
  RegisterPhotoRoute: typeof RegisterPhotoRoute
  RegisterRoleRoute: typeof RegisterRoleRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteRouteChildren: RegisterRouteRouteChildren = {
  RegisterAboutRoute: RegisterAboutRoute,
  RegisterAddressRoute: RegisterAddressRoute,
  RegisterDoneRoute: RegisterDoneRoute,
  RegisterNameRoute: RegisterNameRoute,
  RegisterPhotoRoute: RegisterPhotoRoute,
  RegisterRoleRoute: RegisterRoleRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteRouteWithChildren = RegisterRouteRoute._addFileChildren(
  RegisterRouteRouteChildren,
)

interface ProfileUserIdRouteChildren {
  ProfileUserIdEditRoute: typeof ProfileUserIdEditRoute
}

const ProfileUserIdRouteChildren: ProfileUserIdRouteChildren = {
  ProfileUserIdEditRoute: ProfileUserIdEditRoute,
}

const ProfileUserIdRouteWithChildren = ProfileUserIdRoute._addFileChildren(
  ProfileUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRouteRoute: RegisterRouteRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CreateListingRoute: CreateListingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StyleguideRoute: StyleguideRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
